"""Add curso

Revision ID: 04f8a2c10adf
Revises: 159374ebf4a8
Create Date: 2026-07-16 23:38:06.436064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f8a2c10adf'
down_revision: Union[str, None] = '159374ebf4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('curso', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudiantes', 'curso')
    # ### end Alembic commands ###
