"""Init SQLite

Revision ID: 159374ebf4a8
Revises: 
Create Date: 2026-07-16 00:41:46.515643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159374ebf4a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('diagnostico_pie', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.create_index(op.f('ix_estudiantes_rut'), 'estudiantes', ['rut'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('expedientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedientes_id'), 'expedientes', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('subido_por', sa.Integer(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('procesado_ocr', sa.Boolean(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('pacis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('estado_global', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacis_id'), 'pacis', ['id'], unique=False)
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('pagina', sa.Integer(), nullable=True),
    sa.Column('hallazgo', sa.Text(), nullable=False),
    sa.Column('implicacion_educativa', sa.Text(), nullable=True),
    sa.Column('seccion_paci_sugerida', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_id'), 'evidencias', ['id'], unique=False)
    op.create_table('modulos_paci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paci_id', sa.Integer(), nullable=True),
    sa.Column('tipo_modulo', sa.String(length=100), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('contenido_propuesto', sa.Text(), nullable=True),
    sa.Column('contenido_validado', sa.Text(), nullable=True),
    sa.Column('estado_revision', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paci_id'], ['pacis.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_paci_id'), 'modulos_paci', ['id'], unique=False)
    op.create_table('historial_revisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos_paci.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_revisiones_id'), 'historial_revisiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_revisiones_id'), table_name='historial_revisiones')
    op.drop_table('historial_revisiones')
    op.drop_index(op.f('ix_modulos_paci_id'), table_name='modulos_paci')
    op.drop_table('modulos_paci')
    op.drop_index(op.f('ix_evidencias_id'), table_name='evidencias')
    op.drop_table('evidencias')
    op.drop_index(op.f('ix_pacis_id'), table_name='pacis')
    op.drop_table('pacis')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_expedientes_id'), table_name='expedientes')
    op.drop_table('expedientes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_estudiantes_rut'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_table('estudiantes')
    # ### end Alembic commands ###
