"""SaaS Multi-tenancy

Revision ID: 21e9b0ccc620
Revises: 04f8a2c10adf
Create Date: 2026-07-17 00:17:07.439529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e9b0ccc620'
down_revision: Union[str, None] = '04f8a2c10adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajustes_institucionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institucion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_ajustes_institucionales_institucion_id_instituciones'), 'instituciones', ['institucion_id'], ['id'])

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institucion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_estudiantes_institucion_id_instituciones'), 'instituciones', ['institucion_id'], ['id'])

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institucion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_eventos_institucion_id_instituciones'), 'instituciones', ['institucion_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institucion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_usuarios_institucion_id_instituciones'), 'instituciones', ['institucion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuarios_institucion_id_instituciones'), type_='foreignkey')
        batch_op.drop_column('institucion_id')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_eventos_institucion_id_instituciones'), type_='foreignkey')
        batch_op.drop_column('institucion_id')

    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_estudiantes_institucion_id_instituciones'), type_='foreignkey')
        batch_op.drop_column('institucion_id')

    with op.batch_alter_table('ajustes_institucionales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ajustes_institucionales_institucion_id_instituciones'), type_='foreignkey')
        batch_op.drop_column('institucion_id')

    # ### end Alembic commands ###
